[package]
name = "ade-bridge-solana"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18"
spl-token = "4.0"
borsh = "0.10"

[dev-dependencies]
solana-program-test = "1.18"
solana-sdk = "1.18"

[features]
no-entrypoint = []

